"""
 Generated by typeshare 1.11.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel
from typing import Dict, List, Literal, Union


class ItemDetailsFieldValue(BaseModel):
    hello: str


class AdvancedColorsTypes(str, Enum):
    STRING = "String"
    NUMBER = "Number"
    NUMBER_ARRAY = "NumberArray"
    REALLY_COOL_TYPE = "ReallyCoolType"
    ARRAY_REALLY_COOL_TYPE = "ArrayReallyCoolType"
    DICTIONARY_REALLY_COOL_TYPE = "DictionaryReallyCoolType"

class AdvancedColorsString(BaseModel):
    c: str

class AdvancedColorsNumber(BaseModel):
    c: int

class AdvancedColorsNumberArray(BaseModel):
    c: List[int]

class AdvancedColorsReallyCoolType(BaseModel):
    c: ItemDetailsFieldValue

class AdvancedColorsArrayReallyCoolType(BaseModel):
    c: List[ItemDetailsFieldValue]

class AdvancedColorsDictionaryReallyCoolType(BaseModel):
    c: Dict[str, ItemDetailsFieldValue]

class AdvancedColors(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    t: AdvancedColorsTypes
    c: Union[AdvancedColorsString, AdvancedColorsNumber, AdvancedColorsNumberArray, AdvancedColorsReallyCoolType, AdvancedColorsArrayReallyCoolType, AdvancedColorsDictionaryReallyCoolType]

