"""
 Generated by typeshare 1.11.0
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Annotated, Optional


class Things(BaseModel):
    """
    This is a comment.
    """
    model_config = ConfigDict(populate_by_name=True)

    bla: str
    some_label: Optional[Annotated[str, Field(alias="label")]] = None
    label_left: Optional[Annotated[str, Field(alias="label-left")]] = None


