"""
 Generated by typeshare 1.11.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Literal, Union


class AddressDetails(BaseModel):
    pass

class AddressTypes(str, Enum):
    FIXED_ADDRESS = "FixedAddress"
    NO_FIXED_ADDRESS = "NoFixedAddress"

class AddressFixedAddress(BaseModel):
    content: AddressDetails

class AddressNoFixedAddress(BaseModel):
    content = Literal["NoFixedAddress"]

class Address(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    type: AddressTypes
    content: Union[AddressFixedAddress, AddressNoFixedAddress]

